#!/bin/sh

case "$ENV" in
    ibm*|rackspace) log="/etc/sv/chef-client/log/main/current";;
    *) log="/var/log/chef/client.log";;
esac

sa-ssh -A "tac $log | sed '/INFO: Starting Chef Run/Q;/INFO:\|WARN:\|warning:/d' | tac | head"
