#!/bin/sh

case "$ENV" in
    dev|dev1|devops|hax|meta|qa|ua|myoutlookonline) log="/var/log/chef/client.log";;
    *) log="/etc/sv/chef-client/log/main/current";;
esac

sa-ssh -A "tac $log | sed '/INFO: Starting Chef Run/Q;/INFO:\|WARN:\|warning:/d' | tac | head"
