#!/bin/sh

orgs_file="${DROPBOX_DIR:-$HOME/Dropbox}/Sonian Dev Ops/orgs.csv"

while getopts adnpt: opt; do
    case $opt in
        a) pred="\$2";;
        d) pred="\$2 ~ /^dead/";;
        n) pred="\$2 ~ /^non-prod/";;
        p) pred="\$2 ~ /^prod/";;
        t) pred="\$2 == \"$OPTARG\"";;
    esac
done
shift $(($OPTIND - 1))

if [ "$pred" ]; then
    orgs="$(awk -F, "$pred { print \$1 }" "$orgs_file")"
else
    orgs="$(echo "$1" | sed 's/,/ /g')"; shift
fi

for org in $orgs; do
    test "$org" == "$orgs" || echo "#### ENV=$org"
    ENV="$org" "$@"
done
