#!/bin/sh

export ENV="${ENV:-$(git symbolic-ref -q HEAD | sed s@refs/heads/@@)}"

for inst in "$@"; do
    knife ec2 server delete -y "$inst"
    knife node delete -y "$inst"
    knife client delete -y "$inst"
done
