#!/bin/sh

export ENV="${ENV:-$(git symbolic-ref -q HEAD | sed s@refs/heads/@@)}"

if ! [ -n "$1" -a -n "$2" ]; then
    echo 'usage: knife-ps ROLE_OR_QUERY PROCESS_NAME' 1>&2
    exit 2
fi

sa-ssh -a "$1" "ps aux | grep $(echo "$2" | sed 's/./[&]/') || echo" | nl
