#!/bin/sh

export ENV="${ENV:-$(git symbolic-ref -q HEAD | sed s@refs/heads/@@)}"

while read inst hostname; do
    knife bootstrap "$hostname" -N "$inst" -r "$1" -d ubuntu10.10-gems-sonian -x ubuntu -i "../keys/$ENV.pem" --sudo
done
