#!/usr/bin/ruby

require 'csv'

org_name = ENV['ENV'] || File.basename(%x(git symbolic-ref -q HEAD 2>/dev/null).chomp)
dropbox_dir = ENV['DROPBOX_DIR'] || "#{ENV['HOME']}/Dropbox"
sonian_dir = ENV['SONIAN_DIR'] || "#{ENV['HOME']}/sonian"

orgs = CSV.read("#{dropbox_dir}/Sonian Dev Ops/orgs.csv")
found_org_name, stack_type, email, region = orgs.find {|row| row[0] == org_name }

if email.nil?
  puts "error: couldn't find env '#{org_name}'"
  exit 1
end

creds = CSV.read("#{sonian_dir}/iam/credentials.csv")
account_id, email, username, key, secret = creds.find {|row| row[1] == email }

pem ="#{sonian_dir}/iam/#{email.gsub(/@.*/, '')}.pem"
bin = File.basename($0)

case bin
when 'sa-aws'
  ENV['AWS_ACCESS_KEY_ID'] = key
  ENV['AWS_SECRET_ACCESS_KEY'] = secret
  exec('aws', "--region=#{region}", *ARGV)
when 'sa-rds'
  ENV['EC2_CERT'] = pem
  ENV['EC2_PRIVATE_KEY'] = pem
  ENV['EC2_REGION'] = region
  exec('rds', *ARGV)
else
  STDERR.puts "I don't know how to run as #{bin}"
  exit 2
end
