#!/bin/sh

export ENV="${ENV:-$(git symbolic-ref -q HEAD | sed s@refs/heads/@@)}"

while getopts 123456789ASTak:lstv opt; do
    case $opt in
        [1-9]) n="$opt";;
        A) n="${n:-all}"; query='*:*';;
        S) n=sequential; query='*:*';;
        T) n=tmux; query='*:*';;
        a) n=all;;
        k) knifeopts="$OPTARG";;
        l) n=list;;
        s) n=sequential;;
        t) n=tmux;;
        v) verbose=1;;
    esac
done
shift $(($OPTIND - 1))

if [ -z "$query" ]; then
    case "$1" in
        i-*) query="name:$1";;
        domU-*|ip-*) query="hostname:$1";;
        10.*) query="local_ipv4:$1";;
        lb) query='role:load_balancer';;
        mon|monitor|nagios) query='role:monitoring_server';;
        ws|web|website) query='role:webserver';;
        es|elastic|elasticsearch) query='role:elasticsearch_ebs';;
        es0) query='role:elasticsearch_ebs AND role:search_0';;
        es1) query='role:elasticsearch_ebs AND role:search_1';;
        es2) query='role:elasticsearch_ebs AND role:search_2';;
        es3) query='role:elasticsearch_ebs AND role:search_3';;
        safe0) query='role:safe AND role:search_0';;
        safe1) query='role:safe AND role:search_1';;
        safe2) query='role:safe AND role:search_2';;
        safe3) query='role:safe AND role:search_3';;
        rabbit|amqp) query='role:rabbitmq';;
        gs|gluster) query='role:gluster_server';;
        worker) query='role:safe_worker';;
        bg) query='role:safe_background_worker';;
        nsf) query='role:safe_nsf';;
        nfs) query='role:nfs_server';;
        *:*) query="$1";;
        "") echo 'usage: [ENV=org] sa-ssh [-a] QUERY ARGS...' 1>&2; exit 2;;
        *) query="role:$1";;
    esac
    shift
fi

title() {
    printf "\033]0;$*\007"
}

parsejson() {
    ruby -rjson -e 'JSON.parse(STDIN.read)["rows"].each {|n| puts n["ec2.public_hostname"]}'
}

knifeq() {
    knife search node "$1" -a ec2.public_hostname -Fjson | parsejson
}

knifessh() {
    knife ssh $knifeopts "$1" -a ec2.public_hostname "$2"
}

vssh() {
    test "$verbose" && echo "#### sa-ssh: $1"
    ssh "$@"
}

tpane() {
    if [ "$(tmux list-panes | wc -l)" -gt 5 ]; then
        tmux new-window -d "$@"
    else
        tmux split -d "$@"
        tmux select-layout main-vertical >/dev/null 2>&1
    fi
}

test -t 1 && title "sa-ssh: $query on $ENV"
tmpfile="$(mktemp -t sa-ssh.XXXXXX)"
trap "rm -f '$tmpfile'" EXIT

if knifeq "$query" >"$tmpfile" 2>/dev/null; then
    case "$(grep -c . "$tmpfile")" in
        0) case "$n" in all|list|sequential|tmux);; *) echo 'Error: no nodes found' 1>&2;; esac; exit 1;;
        1) n=1;;
    esac
    if [ -z "$n" ]; then
        nl "$tmpfile"
        printf 'Node number, [a]ll, [s]equential, or [t]mux >> '; read n
    fi
    case "$n" in
        [0-9]*)
            vssh "$(sed -n "${n}p" "$tmpfile")" "$@"
            ;;
        a|all|"")
            knifessh "$query" "${*:-interactive}"
            ;;
        l|list)
            cat "$tmpfile"
            ;;
        s|sequential)
            for h in $(cat "$tmpfile"); do
                vssh "$h" "$@"
            done
            ;;
        t|tmux)
            for h in $(cat "$tmpfile"); do
                tpane "ssh -t $h ${*:+'$*'; read}"
            done
            ;;
        *)
            echo "Error: no node numbered '$n'" 1>&2
            exit 3
            ;;
    esac
else
    echo 'Error: knife query failed' 1>&2
    exit 1
fi
