#!/bin/sh

export ENV="${ENV:-$(git symbolic-ref -q HEAD | sed s@refs/heads/@@)}"

for c in $(git diff --name-only "$@" | grep -v 'metadata\.json$' | grep ^cookbooks | cut -d/ -f2 | sort -u); do
    knife cookbook upload "$c"
done

for f in $(git diff --name-only "$@" | grep ^roles | sort -u); do
    knife role from file "$f"
done
